# Generated by Django 3.2 on 2023-02-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b3_code', models.CharField(max_length=8, unique=True, verbose_name='código do Papel')),
                ('company_name', models.CharField(max_length=50, verbose_name='Nome da empresa')),
                ('last_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cotação')),
                ('logo_url', models.CharField(max_length=50)),
            ],
        ),
    ]
