# Generated by Django 3.2 on 2023-02-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='valor inicial da carteira'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='initial_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='valor inicial da carteira'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Lucro'),
        ),
    ]
