# Generated by Django 3.2 on 2023-02-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userwallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='logo_url',
        ),
    ]
