# Generated by Django 3.2 on 2023-02-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_paper_logo_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
