# Generated by Django 3.2 on 2023-02-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='first_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='cotação'),
        ),
    ]
